/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExamsRouteImport } from './routes/_authenticated/exams'
import { Route as AuthenticatedGradesRouteImport } from './routes/_authenticated/grades'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsRoute = AuthenticatedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGradesRoute = AuthenticatedGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/account': typeof AuthenticatedAccountRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/grades': typeof AuthenticatedGradesRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/students': typeof AuthenticatedStudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/account': typeof AuthenticatedAccountRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/grades': typeof AuthenticatedGradesRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/students': typeof AuthenticatedStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exams': typeof AuthenticatedExamsRoute
  '/_authenticated/grades': typeof AuthenticatedGradesRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/portal'
    | '/account'
    | '/attendance'
    | '/dashboard'
    | '/exams'
    | '/grades'
    | '/groups'
    | '/notifications'
    | '/payments'
    | '/stats'
    | '/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/portal'
    | '/account'
    | '/attendance'
    | '/dashboard'
    | '/exams'
    | '/grades'
    | '/groups'
    | '/notifications'
    | '/payments'
    | '/stats'
    | '/students'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/portal'
    | '/_authenticated/account'
    | '/_authenticated/attendance'
    | '/_authenticated/dashboard'
    | '/_authenticated/exams'
    | '/_authenticated/grades'
    | '/_authenticated/groups'
    | '/_authenticated/notifications'
    | '/_authenticated/payments'
    | '/_authenticated/stats'
    | '/_authenticated/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PortalRoute: typeof PortalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams': {
      id: '/_authenticated/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grades': {
      id: '/_authenticated/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof AuthenticatedGradesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExamsRoute: typeof AuthenticatedExamsRoute
  AuthenticatedGradesRoute: typeof AuthenticatedGradesRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExamsRoute: AuthenticatedExamsRoute,
  AuthenticatedGradesRoute: AuthenticatedGradesRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PortalRoute: PortalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
